version: '3.5'
services:
  express_api:
    container_name: platinum-dev-api-express_api
    build: .
    image: express_api
    user: node
    working_dir: /home/node/app
    labels:
      traefik.backend: "express_api"
      traefik.docker.network: "host"
      traefik.frontend.rule: "Host:platinum-dev.api.chas.school"
    volumes:
      - ./:/home/node/app
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
  database:
    container_name: platinum-dev-api-postgres_db
    image: postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 7772:5432
volumes:
  database:
